apiVersion: 1

datasources:
  # PostgreSQL - Dados de modelos e performance logs
  - name: postgres
    type: postgres
    uid: postgres
    access: proxy
    url: host.docker.internal:5432
    database: automlops_db
    user: automlops_user
    secureJsonData:
      password: '1598'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1300
      timescaledb: false
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    editable: true
    isDefault: true

  # Prometheus - MÃ©tricas de sistema
  - name: prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      timeInterval: '5s'
    editable: true
